blank_issues_enabled: true
contact_links:
  - name: Self-serve Request
    url: https://github.com/pl-strflt/github-mgmt/edit/master/github/pl-strflt.yml
    about: Propose a GitHub configuration change by modifying pl-strflt.yml
