name: Update

on:
  workflow_run:
    workflows:
      - "Apply"
    types:
      - completed
  workflow_dispatch:

jobs:
  update:
    if: (github.event_name == 'workflow_dispatch' &&
        github.ref_name == github.event.repository.default_branch) ||
        (github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion == 'success')
    name: Update
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run build
        working-directory: scripts
      - name: Update PRs
        uses: actions/github-script@v6
        env:
          GITHUB_APP_ID: ${{ secrets.RW_GITHUB_APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ secrets[format('RW_GITHUB_APP_INSTALLATION_ID_{0}', github.repository_owner)] }}
          GITHUB_APP_PEM_FILE: ${{ secrets.RW_GITHUB_APP_PEM_FILE }}
        with:
          script: |
            const {updatePullRequests} = require('scripts/lib/actions/update-pull-requests.js')
            await updatePullRequests(context)
